---
- name: Restart SSH service
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart chronyd service
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: Restart necessary services
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted

- name: Restart systemd
  ansible.builtin.systemd:
    name: systemd
    state: restarted

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Zabbix Agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
