---
dependency:
  name: "galaxy"
  enabled: true

driver:
  name: "docker"

platforms:
  - name: "instance-alma"
    image: "ttanaka9211/docker-systemd:almalinux-9"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/lib/containerd"
    cgroupns_mode: "host"
    privileged: true
    pre_build_image: true
    groups:
      - "rhel_family"

provisioner:
  name: ansible
  retry: 5
  delay: 10
  log: true
  playbooks:
    converge: converge.yml
    verify: verify.yml
